### ISSUE TITLE
Header is not sent in request

### ISSUE THREAD

**Issue by kimmellr** [adafruit/Adafruit_CircuitPython_PyPortal#106]
I was following the Twitter guide on adafruit (https://learn.adafruit.com/twitter-api-use/pyportal-circuitpython-setup) and could not get a response. 

It looks like the header is never passed to the network.fetch function.

Modifying fetch request in the the adafruit_pyportal\__init__.py file to this resolved the issue.

response = self.network.fetch(self.url, headers=self._headers, timeout=timeout)

**Comment by ladyada** [comment]
thanks, can you submit a PR? :)

**Comment by kimmellr** [comment]
I'll look up how to do that!

**Comment by makermelissa** [comment]
Fixed by #107
