### ISSUE TITLE
pyportal_simpletest.py is empty

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_PyPortal#24]
Was it suppose to have something?

**Comment by ladyada** [comment]
hmm i never wrote a simpletest. wanna put the bitcoin demo in?

**Comment by caternuson** [comment]
Sure, can add something. You're thinking this?
https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/PyPortal_Bitcoin

Would it be better to have something that doesn't rely on any assets / subfolders? Not sure what. Just thinking of trying to keep it to one file that needs to be worried about.

**Comment by ladyada** [comment]
oh yeah hmm i guess it could just display on the console then?

**Comment by caternuson** [comment]
Kind of boring, but yah. Grab some text and show it. Like maybe the same text test from here:
https://learn.adafruit.com/adafruit-pyportal/internet-connect#connect-to-wifi-17-5
That would verify wifi / internet / and display are working?

**Comment by ladyada** [comment]
yah agree!

**Comment by caternuson** [comment]
pr merged. version bump?

**Comment by ladyada** [comment]
w0rd!

**Comment by caternuson** [comment]
fixed with #25 
version bumped to 2.1.0

closin, yo.
