### ISSUE TITLE
wait_for_frame fails with CP 5.x

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_PyPortal#53]
Does this call just have to be removed?

https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/blob/master/adafruit_pyportal.py#L553

It seems to work OK if I delete it -- will thst cause any problems for CP 4.x?

```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-alpha.4-72-g7f1bc48a8 on 2019-09-20; Adafruit PyPortal with samd51j20
>>> 
>>> import pyportal_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyportal_simpletest.py", line 10, in <module>
  File "adafruit_pyportal.py", line 245, in __init__
  File "adafruit_pyportal.py", line 243, in __init__
  File "adafruit_pyportal.py", line 553, in play_file
AttributeError: 'Display' object has no attribute 'wait_for_frame'
>>> 
>>> 
```

**Comment by ladyada** [comment]
@tannewt is there any dox on the new screen drawing timing?

**Comment by jerryneedell** [comment]
I removed line 553 and ran it with/without a pyportal_starup.wav on both Cp4.1.0 and CP5.0alpha-4  -- seems to work 
should I put in a PR?

**Comment by tannewt** [comment]
@ladyada The only doc I know of is the API doc here: https://circuitpython.readthedocs.io/en/latest/shared-bindings/displayio/Display.html#displayio.Display.refresh

Thanks @jerryneedell, should be ok to remove.
