### ISSUE TITLE
Default param for text_font

### ISSUE THREAD

**Issue by cpirnat** [adafruit/Adafruit_CircuitPython_PyPortal#72]
Currently text_font on PyPortal class is set to None. Is there a chance we could utilize termalio font for a default font?

**Comment by siddacious** [comment]
What is the issue you are trying to solve? Please give a code example of what you are trying to do that isn't working

**Comment by cpirnat** [comment]
This would assist the helper library in be able to write text to display without the need of manually importing a font by the end user.

**Comment by siddacious** [comment]
That seems useful; can you give a mock example of how you would like it to work? What specific code do you have in mind to write that won't work as is?

`text_font` takes a string path to a font file which `terminalio.FONT` is not, so it would not be as simple as adding a default value.

**Comment by dherrada** [comment]
hi @cpirnat Are you still planning on working on this?

**Comment by makermelissa** [comment]
I implemented this in the MatrixPortal library, so adding it to here should be pretty straightforward. In fact, I may have done this already on a PyPortal and have it floating around somewhere. I think there were only a handful of places special cases needed to be addressed.

**Comment by makermelissa** [comment]
Ah yes, I found it. :)
