### ISSUE TITLE
Demos failing to display images on latest release

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_PyPortal#9]
This was reported on Discord, and has been verified.

With the latest release of PyPortal, if you have a demo that displays an image with or without something (fonts) over it, it will not display. The code will run, and if there are serial prints in the code, those will display on the screen's terminal output.

If you switch to 1.0.3 release, the demos work. I verified this with JP's quote book demo, and the person on Discord verified it with their version of the CuteFuzz demo.

**Comment by ladyada** [comment]
fix here 
https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/pull/10
